//
//  AppDelegate.swift
//  XListing
//
//  Created by Lance on 2015-03-17.
//  Copyright (c) 2015 ZenChat. All rights reserved.
//

import UIKit
//import Fabric
//import Crashlytics
import React

@UIApplicationMain
public final class AppDelegate: UIResponder, UIApplicationDelegate {

    public var window: UIWindow?
    public func startTabBarApplication() {
        appDependencies.startTabBarApplication(window!)
    }
    private var appDependencies: AppDependencies!
    private var _rnBridge: RCTBridge!
    public var rnBridge: RCTBridge {
        return _rnBridge
    }
    
    public func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        var jsCodeLocation: NSURL!
        
        /**
        * Loading JavaScript code - uncomment the one you want.
        *
        * OPTION 1
        * Load from development server. Start the server from the repository root:
        *
        * $ npm start
        *
        * To run on device, change `localhost` to the IP address of your computer
        * (you can get this by typing `ifconfig` into the terminal and selecting the
        * `inet` value under `en0:`) and make sure your computer and iOS device are
        * on the same Wi-Fi network.
        */
        
        #if DEBUG
            jsCodeLocation = NSURL(string: "http://localhost:8081/index.ios.bundle?platform=ios&dev=true")
        #endif
        
        /**
        * OPTION 2
        * Load from pre-bundled file on disk. The static bundle is automatically
        * generated by "Bundle React Native code and images" build step.
        */
        
        #if RELEASE
            jsCodeLocation = NSBundle.mainBundle().URLForResource("main", withExtension: "jsbundle")
        #endif
        
        _rnBridge = RCTBridge(bundleURL: jsCodeLocation, moduleProvider: nil, launchOptions: launchOptions)
        
        // Override point for customization after application launch.
        window = UIWindow(frame: UIScreen.mainScreen().bounds)

        // configure CocoaLumberjack
        Logger.configure()
        
        // connect to LeanCloud
        LeanCloudClient.initialize()
        if let launchOptions = launchOptions {
            LeanCloudClient.trackAppOpenedWithLaunchOptions(launchOptions)
        }
        
        // start background workers
//        backgroundOperationsWorkerFactory.startWorkers()
                
        // start dependency injector
        appDependencies = AppDependencies(window: window!)
        
        // Analytics
//        Fabric.with([Crashlytics.self()])
        
        return true
    }
    
    public func applicationWillResignActive(application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    }

    public func applicationDidEnterBackground(application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    public func applicationWillEnterForeground(application: UIApplication) {
        // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    }

    public func applicationDidBecomeActive(application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    public func applicationWillTerminate(application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
    
}
